apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user-service
                  image: sh4d1/wat-user-service
                  imagePullPolicy: Always
                  command: [
                      "./wat-user-service",
                      "--selector=static",
                      "--server_address=:8080"
                  ]
                  env:
                    - name: DB_HOST
                      value: "postgres:5432"
                    - name: DB_NAME
                      value: "postgres"
                    - name: DB_PASS
                      value: "password"
                    - name: DB_USER
                      value: "postgres"
                  ports:
                      - containerPort: 8080
                        name: user-port
---
apiVersion: v1
kind: Service
metadata:
    name: user
    labels:
        app: user
spec:
    ports:
        - port: 8080
    selector:
        app: user
